export const SESSION_NAMES={
  GU1:'Squat Day',GU2:'Goblet Day',GU3:'Unilateral Day',
  TD1:'Deadlift Day',TD2:'Push Day',TD3:'Upper Body Day',
  CORE1:'Core Session',CORE2:'Core Session',CORE3:'Core Session',
  BW1:'Bodyweight Session',BW2:'Bodyweight Session',BW3:'Bodyweight Session',
  CUSTOM:'Custom Session'
};
export function getSessName(id){return SESSION_NAMES[id]||id;}
export const EXERCISE_LIBRARY=[
  {name:'Back Squat',cat:'GU',equip:['barbell'],muscles:'Quads, glutes, hamstrings',ref:{cue:'Chest up, knees track toes, break parallel.',url:'https://www.youtube.com/embed/ultWZbUMPL8',credit:'CrossFit'}},
  {name:'Romanian Deadlift',cat:'GU',equip:['barbell','dumbbells'],muscles:'Hamstrings, glutes',ref:{cue:'Soft knees, hinge at hips, feel the hamstring stretch.',url:'https://www.youtube.com/embed/KhjNjzrm93c',credit:'Jeff Nippard'}},
  {name:'Conventional Deadlift',cat:'GU',equip:['barbell'],muscles:'Full posterior chain'},
  {name:'Trap Bar Deadlift',cat:'GU',equip:['barbell'],muscles:'Full posterior chain'},
  {name:'KB Goblet Squat',cat:'GU',equip:['kettlebells'],muscles:'Quads, glutes, core',ref:{cue:'Hold at chest, elbows inside knees, sit tall.',url:'https://www.youtube.com/embed/sIX71MwChNg',credit:'Cat & Chau Kettlebell'}},
  {name:'DB Goblet Squat',cat:'GU',equip:['dumbbells'],muscles:'Quads, glutes, core'},
  {name:'KB Romanian Deadlift',cat:'GU',equip:['kettlebells'],muscles:'Hamstrings, glutes',ref:{cue:'Keep KB close to legs, hinge back not down.',url:'https://www.youtube.com/embed/BMyoKmywN40',credit:'iRnsca'}},
  {name:'DB Romanian Deadlift',cat:'GU',equip:['dumbbells'],muscles:'Hamstrings, glutes'},
  {name:'DB Bulgarian Split Squat',cat:'GU',equip:['dumbbells'],muscles:'Quads, glutes, balance',ref:{cue:'Front foot flat, back knee drops straight down.',url:'https://www.youtube.com/embed/2C-uNgKwPLE',credit:'Jeremy Ethier'}},
  {name:'KB Bulgarian Split Squat',cat:'GU',equip:['kettlebells'],muscles:'Quads, glutes, balance',ref:{cue:'Front foot flat, back knee drops straight down.',url:'https://www.youtube.com/embed/2C-uNgKwPLE',credit:'Jeremy Ethier'}},
  {name:'Single Leg Romanian Deadlift',cat:'GU',equip:['dumbbells','kettlebells'],muscles:'Hamstrings, glutes, balance'},
  {name:'DB Reverse Lunge',cat:'GU',equip:['dumbbells'],muscles:'Quads, glutes'},
  {name:'Good Morning',cat:'GU',equip:['barbell'],muscles:'Hamstrings, lower back'},
  {name:'Landmine Press',cat:'GU',equip:['landmine'],muscles:'Shoulders, chest, core rotation',ref:{cue:'Single arm, slight forward lean, press to full extension.',url:'https://www.youtube.com/embed/9OW4SONxuGI',credit:'Sean Hyson'}},
  {name:'Landmine Row',cat:'GU',equip:['landmine'],muscles:'Back, biceps, rotational'},
  {name:'Landmine Rotation',cat:'GU',equip:['landmine'],muscles:'Core, obliques, hips'},
  {name:'Landmine 180',cat:'GU',equip:['landmine'],muscles:'Obliques, rotational power'},
  {name:'Dumbbell Bench Press',cat:'GU',equip:['dumbbells'],muscles:'Chest, shoulders, triceps',ref:{cue:'Dumbbells at chest, controlled path, squeeze at top.',url:'https://www.youtube.com/embed/QsYre__-aro',credit:'ScottHermanFitness'}},
  {name:'DB Incline Press',cat:'GU',equip:['dumbbells'],muscles:'Upper chest, shoulders'},
  {name:'DB Floor Press',cat:'GU',equip:['dumbbells'],muscles:'Chest, triceps'},
  {name:'Dumbbell Row',cat:'GU',equip:['dumbbells'],muscles:'Back, biceps'},
  {name:'DB Chest Supported Row',cat:'GU',equip:['dumbbells'],muscles:'Upper back, rear delts'},
  {name:'KB Windmill',cat:'GU',equip:['kettlebells'],muscles:'Shoulders, obliques, hips'},
  {name:'Barbell Bench Press',cat:'TD',equip:['barbell'],muscles:'Chest, shoulders, triceps',ref:{cue:'Shoulder blades pinched, bar to lower chest, drive up.',url:'https://www.youtube.com/embed/gBZkSn-zsD0',credit:'Buff Dudes'}},
  {name:'Close Grip Bench Press',cat:'TD',equip:['barbell'],muscles:'Triceps, chest'},
  {name:'Barbell Deadlift',cat:'TD',equip:['barbell'],muscles:'Full posterior chain',ref:{cue:'Bar over mid-foot, hinge at hips, push the floor away.',url:'https://www.youtube.com/embed/op9kVnSso6Q',credit:'Alan Thrall'}},
  {name:'Barbell Overhead Press',cat:'TD',equip:['barbell'],muscles:'Shoulders, triceps, core'},
  {name:'Barbell Row',cat:'TD',equip:['barbell'],muscles:'Back, biceps'},
  {name:'Weighted Pull-Ups',cat:'TD',equip:['pullupbar'],muscles:'Lats, biceps, rear delts',ref:{cue:'Dead hang start, squeeze shoulder blades, chin over bar.',url:'https://www.youtube.com/embed/Y3ntNsIS2Q8',credit:'FitnessFAQs'}},
  {name:'Pull-Ups',cat:'TD',equip:['pullupbar'],muscles:'Lats, biceps'},
  {name:'Banded Pull-Ups',cat:'TD',equip:['pullupbar'],muscles:'Lats, biceps'},
  {name:'Chin-Ups',cat:'TD',equip:['pullupbar'],muscles:'Biceps, lats'},
  {name:'EZ Bar Curl',cat:'TD',equip:['ezbar'],muscles:'Biceps, brachialis'},
  {name:'Overhead Tricep Extension',cat:'TD',equip:['ezbar','dumbbells'],muscles:'Triceps'},
  {name:'KB Swing',cat:'TD',equip:['kettlebells'],muscles:'Glutes, hamstrings, core'},
  {name:'KB Clean',cat:'TD',equip:['kettlebells'],muscles:'Full body power'},
  {name:'KB Snatch',cat:'TD',equip:['kettlebells'],muscles:'Full body power, shoulders'},
  {name:'DB Shoulder Press',cat:'TD',equip:['dumbbells'],muscles:'Shoulders, triceps'},
  {name:'DB Arnold Press',cat:'TD',equip:['dumbbells'],muscles:'Full shoulder development'},
  {name:'KB Shoulder Press',cat:'TD',equip:['kettlebells'],muscles:'Shoulders, core stability'},
  {name:'KB Sumo Deadlift',cat:'TD',equip:['kettlebells'],muscles:'Glutes, quads, adductors'},
  {name:'DB Hammer Curl',cat:'TD',equip:['dumbbells'],muscles:'Biceps, brachioradialis'},
  {name:'DB Skull Crusher',cat:'TD',equip:['dumbbells'],muscles:'Triceps'},
  {name:'Tricep Dip',cat:'TD',equip:['bodyweight'],muscles:'Triceps, chest, shoulders'},
  {name:'Inverted Row',cat:'TD',equip:['barbell'],muscles:'Upper back, biceps'},
  {name:'Lateral Raise',cat:'TD',equip:['dumbbells'],muscles:'Lateral delts'},
  {name:'KB Halo',cat:'TD',equip:['kettlebells'],muscles:'Shoulders, rotational stability'},
  {name:'Diamond Push-Up',cat:'TD',equip:['bodyweight'],muscles:'Triceps, chest'},
  {name:'Pike Push-Up',cat:'TD',equip:['bodyweight'],muscles:'Shoulders, upper chest'},
  {name:'Dead Bug',cat:'CORE',equip:['bodyweight'],muscles:'Deep core, anti-rotation'},
  {name:'Hollow Hold',cat:'CORE',equip:['bodyweight'],muscles:'Core, hip flexors'},
  {name:'Copenhagen Plank',cat:'CORE',equip:['bodyweight'],muscles:'Adductors, obliques'},
  {name:'Pallof Press',cat:'CORE',equip:['kettlebells'],muscles:'Anti-rotation, core'},
  {name:'Ab Wheel Rollout',cat:'CORE',equip:['bodyweight'],muscles:'Core, lats, shoulders'},
  {name:'KB Turkish Get-Up',cat:'CORE',equip:['kettlebells'],muscles:'Full body, core stability'},
  {name:'Plank',cat:'CORE',equip:['bodyweight'],muscles:'Core, anti-extension'},
  {name:'Side Plank',cat:'CORE',equip:['bodyweight'],muscles:'Obliques, lateral stability'},
  {name:'Hanging Knee Raise',cat:'CORE',equip:['pullupbar'],muscles:'Abs, hip flexors'},
  {name:'Hanging Leg Raise',cat:'CORE',equip:['pullupbar'],muscles:'Abs, hip flexors'},
  {name:'V-Up',cat:'CORE',equip:['bodyweight'],muscles:'Abs, hip flexors'},
  {name:'Bird Dog',cat:'CORE',equip:['bodyweight'],muscles:'Core, glutes, anti-rotation'},
  {name:'KB Suitcase Carry',cat:'CORE',equip:['kettlebells','dumbbells'],muscles:'Obliques, core, grip'},
  {name:'Farmers Carry',cat:'CORE',equip:['kettlebells','dumbbells'],muscles:'Full body, grip, core'},
  {name:'Russian Twist',cat:'CORE',equip:['bodyweight','kettlebells'],muscles:'Obliques, rotation'},
  {name:'Landmine 180',cat:'CORE',equip:['landmine'],muscles:'Obliques, rotational power'},
  {name:'Push-Up',cat:'BW',equip:['bodyweight'],muscles:'Chest, shoulders, triceps'},
  {name:'Wide Push-Up',cat:'BW',equip:['bodyweight'],muscles:'Chest focus'},
  {name:'Decline Push-Up',cat:'BW',equip:['bodyweight'],muscles:'Upper chest, shoulders'},
  {name:'Pull-Up',cat:'BW',equip:['pullupbar'],muscles:'Lats, biceps'},
  {name:'Chin-Up',cat:'BW',equip:['pullupbar'],muscles:'Biceps, lats'},
  {name:'Squat Jump',cat:'BW',equip:['bodyweight'],muscles:'Explosive legs'},
  {name:'Broad Jump',cat:'BW',equip:['bodyweight'],muscles:'Explosive legs, glutes'},
  {name:'Burpee',cat:'BW',equip:['bodyweight'],muscles:'Full body conditioning'},
  {name:'Mountain Climber',cat:'BW',equip:['bodyweight'],muscles:'Core, conditioning'},
  {name:'Reverse Lunge',cat:'BW',equip:['bodyweight'],muscles:'Quads, glutes'},
  {name:'Single Leg Glute Bridge',cat:'BW',equip:['bodyweight'],muscles:'Glutes, hamstrings, balance'},
  {name:'Glute Bridge',cat:'BW',equip:['bodyweight'],muscles:'Glutes, hamstrings'},
  {name:'Shadow Box',cat:'BW',equip:['bodyweight'],muscles:'Conditioning, boxing technique'},
  {name:'Jump Rope',cat:'BW',equip:['bodyweight'],muscles:'Cardio, footwork, coordination'},
];
export const SESSIONS=[
  {id:'GU1',cat:'GU',name:'GU1 — Barbell',sub:'Back squat led · Barbell focus',equip:['barbell','dumbbells','landmine','bags'],
   warmup:[{name:'Hip 90/90 Rotations',secs:40},{name:'Goblet Squat Hold',secs:30},{name:'Shadow Box',secs:90}],
   exercises:[
    {name:'Back Squat',scheme:'4×5',rest:60,note:'~75-80% max. Control the descent, drive through the floor.',alts:[{name:'Trap Bar Deadlift',reason:'If rack is taken.'},{name:'KB Goblet Squat',reason:'Lower load, same pattern.'}]},
    {name:'Romanian Deadlift',scheme:'3×8-10',rest:60,note:'Barbell or DBs. Posterior chain equals punch power.',alts:[{name:'KB Romanian Deadlift',reason:'KB version.'},{name:'Good Morning',reason:'Similar muscles.'}]},
    {name:'Dumbbell Bench Press',scheme:'3×10-12',rest:60,note:'Shoulder-friendly ROM.',alts:[{name:'Barbell Bench Press',reason:'More load if rack free.'},{name:'DB Floor Press',reason:'Limits ROM.'}]},
    {name:'Dumbbell Row',scheme:'3×10-12 each',rest:60,note:'Chest supported or bent over.',alts:[{name:'Barbell Row',reason:'More total load.'},{name:'Landmine Row',reason:'Rotational pull.'}]},
    {name:'Landmine Press',scheme:'3×8 each',rest:60,note:'Staggered stance, drive from the hip.',alts:[{name:'DB Shoulder Press',reason:'If landmine unavailable.'},{name:'KB Shoulder Press',reason:'Single arm version.'}]},
   ],finisher:'Heavy Bag Intervals - 4x30s hard / 30s rest.'},
  {id:'GU2',cat:'GU',name:'GU2 — KB & DB',sub:'Goblet squat led · No barbell',equip:['kettlebells','dumbbells','bags'],
   warmup:[{name:'Hip 90/90 Rotations',secs:40},{name:'KB Deadlift Hold',secs:30},{name:'Shadow Box',secs:90}],
   exercises:[
    {name:'KB Goblet Squat',scheme:'4×8',rest:60,note:'Hold KB at chest. Sit deep.',alts:[{name:'DB Goblet Squat',reason:'Direct swap.'}]},
    {name:'KB Romanian Deadlift',scheme:'3×10',rest:60,note:'Two KBs. Keep them close to your legs.',alts:[{name:'DB Romanian Deadlift',reason:'Direct swap.'}]},
    {name:'DB Incline Press',scheme:'3×10-12',rest:60,note:'Upper chest focus. Elbows at 45 degrees.',alts:[{name:'Dumbbell Bench Press',reason:'If no incline bench.'},{name:'Pike Push-Up',reason:'Bodyweight option.'}]},
    {name:'DB Chest Supported Row',scheme:'3×10-12 each',rest:60,note:'Face down on incline.',alts:[{name:'Dumbbell Row',reason:'Standing version.'},{name:'Inverted Row',reason:'Bodyweight.'}]},
    {name:'KB Windmill',scheme:'3×6 each',rest:60,note:'Light KB. Shoulder and lateral hip stability.',alts:[{name:'KB Turkish Get-Up',reason:'Full body control.'},{name:'KB Suitcase Carry',reason:'Walk 20m each side.'}]},
   ],finisher:'KB Complex - 4 rounds: 5 swings, 5 cleans, 5 goblet squats. Rest 60s.'},
  {id:'GU3',cat:'GU',name:'GU3 — Unilateral',sub:'Split squat led · Fixes imbalances',equip:['dumbbells','landmine','bags'],
   warmup:[{name:'Hip 90/90 Rotations',secs:40},{name:'Single Leg Glute Bridge',secs:30},{name:'Shadow Box',secs:90}],
   exercises:[
    {name:'DB Bulgarian Split Squat',scheme:'4×8 each',rest:60,note:'Slow descent, front heel drive.',alts:[{name:'DB Reverse Lunge',reason:'Lower balance demand.'},{name:'KB Goblet Squat',reason:'Bilateral fallback.'}]},
    {name:'Single Leg Romanian Deadlift',scheme:'3×8 each',rest:60,note:'DB or KB. Critical for boxing stance.',alts:[{name:'Romanian Deadlift',reason:'Bilateral fallback.'},{name:'KB Swing',reason:'Explosive hinge.'}]},
    {name:'Dumbbell Bench Press',scheme:'3×10-12',rest:60,note:'Keep shoulder blades pinched.',alts:[{name:'DB Floor Press',reason:'Limits ROM.'},{name:'Push-Up',reason:'Bodyweight fallback.'}]},
    {name:'Landmine Row',scheme:'3×10 each',rest:60,note:'Single arm, rotate into the pull.',alts:[{name:'Dumbbell Row',reason:'Direct swap.'},{name:'Inverted Row',reason:'Bodyweight.'}]},
    {name:'Landmine Rotation',scheme:'3×10 each',rest:60,note:'As boxing-specific as it gets.',alts:[{name:'Landmine 180',reason:'Greater range.'},{name:'KB Halo',reason:'More controlled.'}]},
   ],finisher:'Heavy Bag Intervals - 4x30s hard / 30s rest. Focus on hip rotation.'},
  {id:'TD1',cat:'TD',name:'TD1 — Barbell',sub:'Bench & deadlift led',equip:['barbell','ezbar','dumbbells','kettlebells','pullupbar','bags'],
   warmup:[{name:'Thoracic Spine Rotations',secs:40},{name:'Scapular Push-Ups',secs:30},{name:'Shadow Box',secs:90}],
   exercises:[
    {name:'Barbell Bench Press',scheme:'4×5',rest:60,note:'~75-80% max. Controlled descent, powerful press.',alts:[{name:'Dumbbell Bench Press',reason:'If no rack free.'},{name:'DB Floor Press',reason:'Limits ROM.'}]},
    {name:'Barbell Deadlift',scheme:'3×5',rest:60,note:'Conventional. Full reset each rep.',alts:[{name:'Trap Bar Deadlift',reason:'More knee-friendly.'},{name:'KB Sumo Deadlift',reason:'No barbell fallback.'}]},
    {name:'Weighted Pull-Ups',scheme:'4×6-8',rest:60,note:'Add DB between feet when bodyweight is easy.',alts:[{name:'Banded Pull-Ups',reason:'Band reduces load.'},{name:'Inverted Row',reason:'Fully scalable.'}]},
    {name:'EZ Bar Curl',scheme:'3×10-12',rest:60,note:'Superset with triceps to save time.',alts:[{name:'DB Hammer Curl',reason:'Neutral grip variation.'}]},
    {name:'Overhead Tricep Extension',scheme:'3×10-12',rest:60,note:'EZ Bar or DB. Superset with curls.',alts:[{name:'DB Skull Crusher',reason:'Lying version.'},{name:'Tricep Dip',reason:'Bodyweight.'}]},
    {name:'KB Swing',scheme:'3×15',rest:60,note:'Builds the snap in your punches.',alts:[{name:'KB Clean',reason:'More complex hip power.'}]},
   ],finisher:'AMRAP 6 min - 10 KB swings, 8 push-ups, 6 reverse lunges.'},
  {id:'TD2',cat:'TD',name:'TD2 — DB & KB',sub:'Shoulder press led · No barbell',equip:['dumbbells','kettlebells','bags'],
   warmup:[{name:'Thoracic Spine Rotations',secs:40},{name:'Scapular Push-Ups',secs:30},{name:'Shadow Box',secs:90}],
   exercises:[
    {name:'DB Shoulder Press',scheme:'4×8-10',rest:60,note:'Drive overhead. Do not arch lower back.',alts:[{name:'KB Shoulder Press',reason:'Single arm version.'},{name:'DB Arnold Press',reason:'Full shoulder development.'}]},
    {name:'KB Sumo Deadlift',scheme:'3×10',rest:60,note:'Wide stance, two KBs. As heavy as possible.',alts:[{name:'DB Romanian Deadlift',reason:'More hamstring focus.'}]},
    {name:'DB Chest Supported Row',scheme:'3×10-12 each',rest:60,note:'Face down on incline.',alts:[{name:'Dumbbell Row',reason:'Standing version.'}]},
    {name:'DB Hammer Curl',scheme:'3×10-12',rest:60,note:'Hits brachialis and brachioradialis.',alts:[{name:'EZ Bar Curl',reason:'More load option.'}]},
    {name:'DB Skull Crusher',scheme:'3×10-12',rest:60,note:'Lying. Superset with curls.',alts:[{name:'Overhead Tricep Extension',reason:'Standing version.'},{name:'Tricep Dip',reason:'Bodyweight.'}]},
    {name:'KB Swing',scheme:'3×15',rest:60,note:'Hinge hard at the hip.',alts:[{name:'KB Clean',reason:'More complex.'}]},
   ],finisher:'AMRAP 6 min - 10 KB swings, 8 push-ups, 6 reverse lunges.'},
  {id:'TD3',cat:'TD',name:'TD3 — Bodyweight Upper',sub:'Minimal equipment',equip:['bodyweight','kettlebells','pullupbar'],
   warmup:[{name:'Thoracic Spine Rotations',secs:40},{name:'Scapular Push-Ups',secs:30},{name:'Shadow Box',secs:90}],
   exercises:[
    {name:'Weighted Pull-Ups',scheme:'4×max',rest:60,note:'Add weight if easy, band if hard.',alts:[{name:'Inverted Row',reason:'More horizontal equals harder.'},{name:'Dumbbell Row',reason:'If no bar.'}]},
    {name:'Pike Push-Up',scheme:'3×10-12',rest:60,note:'Overhead press mechanics bodyweight.',alts:[{name:'DB Shoulder Press',reason:'If bodyweight too limited.'},{name:'Diamond Push-Up',reason:'Tricep focused.'}]},
    {name:'KB Swing',scheme:'3×15',rest:60,note:'Explosive hip hinge.',alts:[{name:'KB Clean',reason:'More complex.'}]},
    {name:'Inverted Row',scheme:'3×10-12',rest:60,note:'More horizontal equals harder.',alts:[{name:'Dumbbell Row',reason:'If setup not available.'}]},
    {name:'Diamond Push-Up',scheme:'3×10-12',rest:60,note:'Pause at bottom.',alts:[{name:'Overhead Tricep Extension',reason:'Load the triceps.'},{name:'Tricep Dip',reason:'Bodyweight dip.'}]},
    {name:'KB Halo',scheme:'3×10 each',rest:60,note:'Shoulder stability and rotation.',alts:[{name:'KB Suitcase Carry',reason:'Core and shoulder stability.'}]},
   ],finisher:'AMRAP 6 min - 10 push-ups, 8 KB swings, 6 burpees.'},
  {id:'CORE1',cat:'CORE',name:'Core 1 — Foundation',sub:'Anti-rotation · Stability focus',equip:['bodyweight','kettlebells'],
   warmup:[{name:'Cat-Cow Stretch',secs:30},{name:'Dead Bug Hold',secs:20},{name:'Shadow Box',secs:60}],
   exercises:[
    {name:'Dead Bug',scheme:'3×10 each',rest:45,note:'Lower opposite arm and leg slowly.',alts:[{name:'Bird Dog',reason:'Similar demand, easier.'},{name:'Plank',reason:'Static fallback.'}]},
    {name:'Hollow Hold',scheme:'3×30s',rest:45,note:'Arms overhead, lower back pressed to floor.',alts:[{name:'Plank',reason:'Easier.'},{name:'Ab Wheel Rollout',reason:'Progressive step.'}]},
    {name:'Copenhagen Plank',scheme:'3×20s each',rest:45,note:'Side plank with top foot on bench.',alts:[{name:'Side Plank',reason:'Easier version.'},{name:'KB Suitcase Carry',reason:'Walk 20m each side.'}]},
    {name:'Pallof Press',scheme:'3×10 each',rest:45,note:'Anti-rotation. Use KB or band.',alts:[{name:'Bird Dog',reason:'Bodyweight fallback.'}]},
    {name:'KB Suitcase Carry',scheme:'3×20m each',rest:45,note:'Heavy KB in one hand. Walk tall.',alts:[{name:'Side Plank',reason:'Static lateral core.'}]},
   ],finisher:'3 rounds: 30s plank, 15s hollow hold, 30s rest.'},
  {id:'CORE2',cat:'CORE',name:'Core 2 — Rotational Power',sub:'Boxing-specific · Hip rotation',equip:['kettlebells','landmine'],
   warmup:[{name:'Hip Circles',secs:30},{name:'Cat-Cow',secs:30},{name:'Shadow Box',secs:60}],
   exercises:[
    {name:'Landmine Rotation',scheme:'3×12 each',rest:60,note:'Rotate through hips, not just arms.',alts:[{name:'Landmine 180',reason:'Greater range.'},{name:'KB Halo',reason:'More controlled.'}]},
    {name:'KB Turkish Get-Up',scheme:'3×3 each',rest:90,note:'Light KB. One of the best exercises in existence.',alts:[{name:'Dead Bug',reason:'Lower demand.'}]},
    {name:'Landmine 180',scheme:'3×10 each',rest:60,note:'Builds hip rotation power for hooks.',alts:[{name:'Landmine Rotation',reason:'Shorter range.'},{name:'Russian Twist',reason:'Bodyweight rotation.'}]},
    {name:'Hanging Leg Raise',scheme:'3×10',rest:60,note:'Controlled. Do not swing.',alts:[{name:'Hanging Knee Raise',reason:'Easier.'},{name:'V-Up',reason:'Floor version.'}]},
    {name:'Ab Wheel Rollout',scheme:'3×8',rest:60,note:'Slow out, controlled back. Start from knees.',alts:[{name:'Dead Bug',reason:'Lower demand.'}]},
   ],finisher:'3 rounds: 10 Landmine rotations each side, 10 hanging knee raises, 30s rest.'},
  {id:'CORE3',cat:'CORE',name:'Core 3 — Finisher Circuit',sub:'Add to any session · 6 minutes',equip:['bodyweight','kettlebells'],
   warmup:[],
   exercises:[
    {name:'Plank',scheme:'3×45s',rest:15,note:'Brace hard. Hips level.',alts:[{name:'Hollow Hold',reason:'More demanding.'}]},
    {name:'Side Plank',scheme:'3×30s each',rest:15,note:'Stack feet or stagger.',alts:[{name:'Copenhagen Plank',reason:'More demanding.'}]},
    {name:'V-Up',scheme:'3×12',rest:20,note:'Meet hands and feet at top.',alts:[{name:'Hanging Knee Raise',reason:'If bar available.'}]},
    {name:'Bird Dog',scheme:'3×10 each',rest:20,note:'Opposite arm and leg. Slow and controlled.',alts:[{name:'Dead Bug',reason:'Similar demand.'}]},
   ],finisher:'None - this session IS the finisher.'},
  {id:'BW1',cat:'BW',name:'BW1 — Full Body Power',sub:'No equipment · Explosive focus',equip:['bodyweight'],
   warmup:[{name:'Arm Circles',secs:20},{name:'Leg Swings',secs:20},{name:'Shadow Box',secs:90}],
   exercises:[
    {name:'Squat Jump',scheme:'4×8',rest:60,note:'Land soft. Explosive drive upward.',alts:[{name:'Broad Jump',reason:'Horizontal power.'}]},
    {name:'Push-Up',scheme:'4×12',rest:60,note:'Full range. Pause at bottom.',alts:[{name:'Diamond Push-Up',reason:'Tricep focus.'},{name:'Decline Push-Up',reason:'Upper chest.'}]},
    {name:'Pull-Up',scheme:'4×max',rest:60,note:'Dead hang start, full extension.',alts:[{name:'Chin-Up',reason:'More bicep.'},{name:'Inverted Row',reason:'Easier.'}]},
    {name:'Burpee',scheme:'3×10',rest:60,note:'Full extension at top.',alts:[{name:'Mountain Climber',reason:'Lower impact.'}]},
    {name:'Single Leg Glute Bridge',scheme:'3×12 each',rest:45,note:'Full hip extension at top.',alts:[{name:'Glute Bridge',reason:'Both legs.'}]},
   ],finisher:'Tabata: 20s work / 10s rest x8 - push-ups and squat jumps alternating.'},
  {id:'BW2',cat:'BW',name:'BW2 — Upper Body',sub:'Push and pull · Pull-up bar helpful',equip:['bodyweight','pullupbar'],
   warmup:[{name:'Arm Circles',secs:20},{name:'Scapular Push-Ups',secs:20},{name:'Shadow Box',secs:90}],
   exercises:[
    {name:'Pull-Up',scheme:'5×max',rest:60,note:'Aim to add reps each week.',alts:[{name:'Chin-Up',reason:'Bicep focused.'},{name:'Inverted Row',reason:'Scalable fallback.'}]},
    {name:'Wide Push-Up',scheme:'4×12',rest:60,note:'Wide grip for chest focus.',alts:[{name:'Push-Up',reason:'Standard.'},{name:'Decline Push-Up',reason:'Upper chest.'}]},
    {name:'Diamond Push-Up',scheme:'3×10',rest:60,note:'Tricep focus. Pause at bottom.',alts:[{name:'Pike Push-Up',reason:'Shoulder focus.'}]},
    {name:'Inverted Row',scheme:'3×12',rest:60,note:'More horizontal equals harder.',alts:[{name:'Pull-Up',reason:'If this becomes easy.'}]},
    {name:'Pike Push-Up',scheme:'3×10',rest:60,note:'Shoulder press mechanics.',alts:[{name:'Diamond Push-Up',reason:'Tricep focused.'}]},
   ],finisher:'3 rounds: max pull-ups, 20 push-ups, 60s rest.'},
  {id:'BW3',cat:'BW',name:'BW3 — Boxing Conditioning',sub:'Shadow boxing · No equipment',equip:['bodyweight'],
   warmup:[{name:'Shadow Box',secs:120},{name:'Hip Circles',secs:30},{name:'Arm Circles',secs:20}],
   exercises:[
    {name:'Shadow Box',scheme:'4×2min',rest:60,note:'Technique and movement. Every punch with intent.',alts:[{name:'Mountain Climber',reason:'Conditioning fallback.'},{name:'Burpee',reason:'Full body power.'}]},
    {name:'Burpee',scheme:'4×10',rest:60,note:'Full extension at top.',alts:[{name:'Squat Jump',reason:'Lower impact.'}]},
    {name:'Mountain Climber',scheme:'3×20 each',rest:45,note:'Keep hips level.',alts:[{name:'Plank',reason:'Static version.'}]},
    {name:'Single Leg Glute Bridge',scheme:'3×10 each',rest:45,note:'Balance and hip strength.',alts:[{name:'Glute Bridge',reason:'Bilateral fallback.'}]},
    {name:'Jump Rope',scheme:'3×90s',rest:45,note:'Double-unders when comfortable.',alts:[{name:'Shadow Box',reason:'If no rope.'}]},
   ],finisher:'3 rounds: 30s shadow box, 10 burpees, 60s rest.'},
];
export const CAT_META={
  GU:{label:'Ground Up',color:'var(--red)',abtn:'ab-r'},
  TD:{label:'Top Down',color:'var(--blue)',abtn:'ab-b'},
  CORE:{label:'Core',color:'var(--green)',abtn:'ab-gr'},
  BW:{label:'Bodyweight',color:'var(--muted)',abtn:'ab-gh'},
  CUSTOM:{label:'Custom',color:'var(--purple)',abtn:'ab-p'},
};
export const TRACKED_LIFTS=[
  {name:'Back Squat',color:'#E6A817',sess:'GU',sessLabel:'Ground Up'},
  {name:'Barbell Deadlift',color:'#E6A817',sess:'TD',sessLabel:'Top Down'},
  {name:'Barbell Bench Press',color:'#E6A817',sess:'TD',sessLabel:'Top Down'},
  {name:'Romanian Deadlift',color:'#E6A817',sess:'GU',sessLabel:'Ground Up'},
  {name:'Weighted Pull-Ups',color:'#E6A817',sess:'TD',sessLabel:'Top Down'},
];
export const EQUIP_OPTIONS=[
  {id:'barbell',label:'Barbell & Rack'},{id:'dumbbells',label:'Dumbbells'},
  {id:'kettlebells',label:'Kettlebells'},{id:'ezbar',label:'EZ Bar'},
  {id:'pullupbar',label:'Pull-Up Bar'},{id:'landmine',label:'Landmine'},
  {id:'bags',label:'Punch Bags'},{id:'bodyweight',label:'Bodyweight'},
];
export const PUNCH_NAMES={1:'Jab',2:'Cross',3:'Left Hook',4:'Right Hook',5:'Left Uppercut',6:'Right Uppercut'};
export const DEF_DISP={'slip-l':'SL','slip-r':'SR','roll':'RL','roll-r':'RR','step':'ST'};
export const DEF_CALL={'slip-l':'Slip left','slip-r':'Slip right','roll':'Roll left','roll-r':'Roll right','step':'Step out'};
export const COMBO_TIERS={
  basics:{label:'Basics',intro:'Start here. Clean punches, good habits.',combos:[
    {name:'The Jab',seq:[1],desc:'Single jab. Snap it out, bring it back.'},
    {name:'The Cross',seq:[2],desc:'Single right hand. Power from the hip.'},
    {name:'One-Two',seq:[1,2],desc:'The foundation. Jab sets it up, cross finishes.'},
    {name:'Double Jab',seq:[1,1],desc:'Two jabs. First measures distance, second lands.'},
    {name:'Two-One',seq:[2,1],desc:'Cross then jab. Catches them off guard.'},
    {name:'Triple Jab',seq:[1,1,1],desc:'Three jabs. Control range, keep them guessing.'},
    {name:'One-Two-One',seq:[1,2,1],desc:'Classic. End with the jab to reset your guard.'},
    {name:'Double Jab Cross',seq:[1,1,2],desc:'Two jabs to find the range, cross to finish.'},
  ]},
  amateur:{label:'Amateur',intro:'Hooks, uppercuts, and you start moving.',combos:[
    {name:'One-Two-Three',seq:[1,2,3],desc:'Jab, cross, left hook. The classic three-punch combination.'},
    {name:'One-Two-Four',seq:[1,2,4],desc:'Jab, cross, right hook.'},
    {name:'One-Three-Two',seq:[1,3,2],desc:'Jab, hook, cross. Change the rhythm.'},
    {name:'Slip and Cross',seq:['slip-r',2],desc:'Slip their jab, fire the cross back.'},
    {name:'Slip and Hook',seq:['slip-l',3],desc:'Slip outside, left hook follows.'},
    {name:'One-Two-Roll',seq:[1,2,'roll'],desc:'One-two then roll under their counter.'},
    {name:'Roll and Cross',seq:['roll',2],desc:'Roll under their hook, come up with the cross.'},
    {name:'One-Two-Three-Two',seq:[1,2,3,2],desc:'Four punches. End with the right hand.'},
    {name:'Step and Jab',seq:['step',1,1],desc:'Step to the side, two jabs from the angle.'},
    {name:'One-Two-Five',seq:[1,2,5],desc:'Jab, cross, left uppercut. Level change.'},
    {name:'Double Hook',seq:[3,4],desc:'Left hook, right hook. Short range.'},
    {name:'Roll and Uppercut',seq:['roll',5,2],desc:'Roll under, come up with uppercut, cross.'},
  ]},
  pro:{label:'Pro',intro:'Five and six punch combinations.',combos:[
    {name:'Five Punch Combo',seq:[1,2,3,2,3],desc:'Jab, cross, hook, cross, hook. Relentless.'},
    {name:'Body Head',seq:[1,3,2],desc:'Jab to the body, hook to the head, cross.'},
    {name:'Six Punch Barrage',seq:[1,1,2,3,2,3],desc:'Double jab to open, four hard shots to follow.'},
    {name:'Body Body Head',seq:[2,3,2],desc:'Body cross, body hook, head cross.'},
    {name:'Slip Cross Roll Hook',seq:['slip-r',2,'roll',3],desc:'Slip, power shot, roll, hook.'},
    {name:'Uppercut Combo',seq:[1,2,5,6,3],desc:'Jab-cross, two uppercuts, hook.'},
    {name:'The Pressure Combo',seq:[1,2,3,2,5,2],desc:'Six punches. Do not stop.'},
    {name:'Step and Punish',seq:['step',1,2,3,2],desc:'Step to angle, then four shots.'},
    {name:'Philly Shell Counter',seq:['slip-r',2,'roll',3],desc:'Slip, cross, roll, left hook.'},
    {name:'Double Jab Body Head',seq:[1,1,3,2],desc:'Two jabs, body hook, cross upstairs.'},
  ]},
  champ:{label:'Champion',intro:'Champion-level combinations.',combos:[
    {name:'The Ali Shuffle',seq:[1,1,1,2],desc:'Three rapid jabs, then the cross.'},
    {name:'Ali Jab Sequence',seq:[1,1,2,1],desc:'Double jab, cross, reset jab.'},
    {name:'Tyson Peek-a-Boo',seq:['roll',1,2,3],desc:'Roll under, explosive jab-cross-hook.'},
    {name:'Tyson Body Assault',seq:[1,3,2,3,2],desc:'Jab to open, alternating hooks and crosses.'},
    {name:'Pacquiao Angle',seq:[1,2,'step',1,2,3],desc:'One-two, step, one-two-three from new position.'},
    {name:'Pacquiao Southpaw Barrage',seq:[2,3,2,3,2],desc:'Volume punching from a southpaw angle.'},
    {name:'Canelo Counter',seq:['slip-r',2,3,2],desc:'Slip outside the jab, cross-hook-cross.'},
    {name:'Canelo Roll and Uppercut',seq:['roll',5,2,3],desc:'Roll under, left uppercut, cross, hook.'},
    {name:'Floyd Shoulder Roll',seq:['slip-r',2,3,2,3],desc:'Roll off jab, explode back with four shots.'},
    {name:'The Championship Round',seq:[1,1,2,3,2,5,3,2],desc:'Eight punches. Leave nothing in the tank.'},
  ]},
};
export const LEGEND_COMBOS=[
  {name:'Muhammad Ali',style:'Float like a butterfly, sting like a bee',
   intro:"Ali built everything on speed, feints and angles. The jab was his paintbrush — it measured range, set up the cross, and kept opponents honest. Stay light on your feet.",
   combos:[
    {name:'The Ali Shuffle Entry',seq:[1,1,2,3,2],desc:'Double jab to create confusion, cross-hook-cross to finish. Stay light on your feet.'},
   ]},
  {name:'Mike Tyson',style:'Bad intentions. Every single time.',
   intro:"Tyson used the peek-a-boo to get inside and do damage. The jab was a probe — the real work started once he was in close. Get there and finish.",
   combos:[
    {name:'The Tyson Peek-a-Boo',seq:[1,'slip-l',2,3],desc:'Jab to draw the counter, slip outside, cross and hook together. Get in close.'},
   ]},
  {name:'Sugar Ray Leonard',style:'Speed, footwork and explosive combination punching',
   intro:"Leonard had everything. The feint and the roll were weapons in their own right — they created openings that the combination then punished. Rhythm is everything.",
   combos:[
    {name:'The Sugar Ray',seq:[1,2,'roll',3,2],desc:'Jab-cross, roll under the hook, come back with hook-cross. Rhythm is everything.'},
    {name:'The Leonard Feint',seq:[1,1,'slip-l',2,5,3],desc:'Double jab feint, slip your own line, cross-lead uppercut-hook. Catch them guessing.'},
   ]},
  {name:'Joe Frazier',style:'Come forward. Never stop. Make them feel it.',
   intro:"Frazier's pressure was relentless. He used the jab and cross to find range, then went to the body to drag the guard down. The hook upstairs came when the opening appeared.",
   combos:[
    {name:'The Frazier Pressure',seq:[1,2,'b2',3],desc:'Standard opener, body cross to drop the guard, lead hook upstairs. Keep moving forward.'},
   ]},
  {name:'Manny Pacquiao',style:'Relentless angles and impossible volume',
   intro:"Pacquiao threw combinations, not punches. Every shot set up the next. He came at angles you couldn't predict and threw volume you couldn't answer.",
   combos:[
    {name:'The Pacquiao Blitz',seq:[1,2,3,2,3,2],desc:'Six punch combination at full pace. Every punch sets up the next. Don\'t stop.'},
   ]},
  {name:'Floyd Mayweather',style:'Defence is offence. Read, slip, and make them pay.',
   intro:"Mayweather made the shoulder roll a weapon. The slip wasn't just defensive — it was a trap that put him in the perfect position to counter. Every movement had a purpose.",
   combos:[
    {name:'The Mayweather Counter',seq:['slip-l',2,3,2],desc:'Slip the jab, shoulder roll into cross-hook-cross. Defence into offence.'},
   ]},
  {name:'George Foreman',style:'Establish range. Attack the body. End it.',
   intro:"Foreman used his jab to measure and his right hand to finish. The body hook in between bent opponents and made the final cross land clean. Power through everything.",
   combos:[
    {name:'The Foreman Closer',seq:[1,2,'b3',2],desc:'Establish range with jab-cross, body hook to bend them, finishing cross. Power through.'},
   ]},
  {name:'Marvin Hagler',style:'March forward. Mix levels. Never give them a rest.',
   intro:"Hagler walked opponents down and mixed head and body constantly. You could never settle because you never knew where the next shot was coming from.",
   combos:[
    {name:'The Hagler March',seq:[1,'b2',3,'b4',2],desc:'Alternate head and body throughout. Never stay on one level. Keep walking them down.'},
   ]},
  {name:'Bernard Hopkins',style:'Every move has a plan. Control the distance.',
   intro:"Hopkins was a chess player. He smothered offence, rolled away from danger, went to the body to slow opponents down, then picked his shots upstairs. Surgical and patient.",
   combos:[
    {name:'The Hopkins Smother',seq:[1,2,'roll-r','b2',3],desc:'Jab-cross, roll away from the counter, body cross and hook. Control the distance.'},
   ]},
  {name:'Oscar De La Hoya',style:'Classic technique with real finishing power',
   intro:"De La Hoya combined technical boxing with genuine power. The slip outside gave him the angle to double up on the finish — always balanced, always in position to hit.",
   combos:[
    {name:'The De La Hoya',seq:[1,2,3,'slip-l',2,3],desc:'Classic combination, slip outside, double up on the finish. Stay balanced throughout.'},
   ]},
  {name:'Roberto Duran',style:'Come in low. Make them feel the body. Take the head.',
   intro:"Duran came in low and made you feel everything. The body jabs and crosses set up the hook upstairs — by the time the head shot came, you were already hurt.",
   combos:[
    {name:'The Duran Brawl',seq:['b1','b2',3,2],desc:'Come in low with body jabs and crosses, hook upstairs to straighten them up, finishing cross.'},
   ]},
  {name:'Joe Calzaghe',style:'High output. Relentless pace. Never let them settle.',
   intro:"Calzaghe threw more punches than anyone at world level and never let pace drop. Speed over power — the combination works because it never stops.",
   combos:[
    {name:'The Calzaghe Volume',seq:[1,2,3,4,1,2],desc:'High output combination. Speed over power. Keep the pressure constant.'},
   ]},
  {name:'Amir Khan',style:'Explosive speed. Get in range fast and finish.',
   intro:"Khan brought hand speed that most opponents had never seen. The double jab gets him into range, the roll takes him off the counter line, and the three-punch finish comes before you can react.",
   combos:[
    {name:'The Khan Entry',seq:[1,1,2,'roll',3,2,3],desc:'Double jab to get in range, cross, roll under, three punch finish. Explosive start.'},
   ]},
  {name:'Sonny Liston',style:'Cut off the ring. Work the body. Break them down.',
   intro:"Liston was methodical and devastating. He used the jab to control distance and position, then attacked the body systematically before going upstairs. Stay patient — the finish comes.",
   combos:[
    {name:'The Liston Stalk',seq:[1,2,'b3','b4',2,3],desc:'Systematic body work to break down the guard, finish upstairs. Stay patient.'},
   ]},
  {name:'Thomas Hearns',style:'The right hand ends it. Every punch is a threat.',
   intro:"Hearns had the reach and the right hand to end any fight. This combination looks simple because it is — the threat of the right hand is what makes every other punch work.",
   combos:[
    {name:'The Hearns',seq:[1,2,3,2],desc:'Simple but thrown at maximum power. Every punch a threat. The right hand ends it.'},
   ]},
  {name:'Andre Ward',style:'Nothing wasted. Everything connected.',
   intro:"Ward won every close fight because he never wasted a punch. The slip takes him off the jab line, the body shot forces a reaction, and the combination upstairs follows the reaction.",
   combos:[
    {name:'The Ward Control',seq:[1,'slip-l','b2',3,2],desc:'Jab to establish, slip, go to the body, come back upstairs with hook-cross. Surgical.'},
   ]},
  {name:'Julio César Chávez',style:'Cut off the ring. Attack the body. Grind them down.',
   intro:"Chávez was relentless and systematic. He used the jab to cut off the escape routes, went to the body to slow opponents down, then closed with the cross when they had nowhere to go.",
   combos:[
    {name:'The Chavez Cut Off',seq:[1,2,'b2','b3',2],desc:'Use the jab to cut off the ring, attack the body to slow them down, finish with the cross.'},
   ]},
  {name:'Canelo Álvarez',style:'Patient, accurate, then devastating.',
   intro:"Canelo waits longer than you expect and makes you pay harder than you expected. The body hook is the trap — it pulls the guard down for the shots that follow.",
   combos:[
    {name:'The Canelo Switch',seq:[1,2,'roll','b3',2,3],desc:'Jab-cross, roll under the return, body hook, cross, lead hook. Read their reaction.'},
   ]},
  {name:'The Championship Round',style:'Save this for when you\'re ready.',
   intro:"Eight punches in sequence. Not for beginners. Throw it clean or don't throw it at all.",
   combos:[
    {name:'The Championship Round',seq:[1,1,2,3,2,5,3,2],desc:'Eight punch combination. Save this for when you\'re fit and fast enough to throw it clean.'},
   ]},
];
export const TIER_DESCS={basics:'Single punches and fundamental combinations',amateur:'Two and three punch combinations with movement',pro:'Four and five punch combinations',champ:'Complex combinations with defensive moves',legends:'Elite level — championship combinations',mycombos:'Combinations you\'ve built and saved'};
export const CORNER_QUOTES=[
  {text:"Every round you survive is a round you've won.",attr:"Corner"},
  {text:"You're not tired. Tired is a feeling. Right now you're just working.",attr:"Corner"},
  {text:"Keep your hands up. Every. Single. Second.",attr:"Corner"},
  {text:"Don't think - throw.",attr:"Corner"},
  {text:"Move your head. A moving target is a hard target.",attr:"Corner"},
  {text:"When you want to stop, that's when the other guy is feeling it too.",attr:"Corner"},
  {text:"Breathe. You forget to breathe, everything falls apart.",attr:"Corner"},
  {text:"Champions are made in the rounds they want to quit.",attr:"Cus D'Amato"},
  {text:"Fear is the greatest obstacle to learning.",attr:"Cus D'Amato"},
  {text:"The hero and the coward both feel the same thing. What matters is what the hero does with it.",attr:"Cus D'Amato"},
  {text:"The jab. Use the jab. Everything starts with the jab.",attr:"Corner"},
  {text:"Anyone can be beaten. The question is whether you believe it.",attr:"Corner"},
];
export const ACCENT_COLORS=[{val:'#E63946'},{val:'#457B9D'},{val:'#E6A817'},{val:'#2ecc71'},{val:'#8B5CF6'},{val:'#F4623A'},{val:'#0EA5E9'},{val:'#f0f0f0'}];
